apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: influxdb
    port: 8086
    protocol: TCP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: sehattor/influxdb:v1
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: var/lib/influxdb
        livenessProbe:
          exec:
            command: ["ash", "./livenessprobe.sh"]
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: influxdb
  hostPath:
    path: /data/influxdb-pv
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: influxdb

