apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: sehattor/mysql:v1
        imagePullPolicy: Never
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: var/lib/mysql
        livenessProbe:
          exec:
            command: ["ash", "./livenessprobe.sh"]
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - name: influxdb-service
        image: sehattor/mysql:v1
        imagePullPolicy: Never
        command: ['sh', '-c', 'until nc -z influxdb-service 8086; do echo waiting for influxdb-service 8086; sleep 2; done;']
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql
  hostPath:
    path: /data/mysql-pv
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mysql
