apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-service"
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: https
    port: 3000
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: sehattor/grafana
        imagePullPolicy: Never
      initContainers:
      - name: influxdb-service
        image: sehattor/grafana
        imagePullPolicy: Never
        command: ['sh', '-c', 'until nc -z influxdb-service 8086; do echo waiting for influxdb-service 8086; sleep 2; done;']