apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-service"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  - name: ssh
    port: 22
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sehattor/nginx:v1
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["ash", "./livenessprobe.sh"]
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - name: influxdb-service
        image: sehattor/nginx:v1
        imagePullPolicy: Never
        command: ['sh', '-c', 'until nc -z influxdb-service 8086; do echo waiting for influxdb-service 8086; sleep 2; done;']