apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-service"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: https
    port: 5050
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: sehattor/wordpress
        imagePullPolicy: Never
