apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-service"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: https
    port: 5050
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: sehattor/wordpress:v1
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["ash", "./livenessprobe.sh"]
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - name: influxdb-service
        image: sehattor/wordpress:v1
        imagePullPolicy: Never
        command: ['sh', '-c', 'until nc -z influxdb-service 8086; do echo waiting for influxdb-service 8086; sleep 2; done;']
      - name: mysql-service
        image: sehattor/wordpress:v1
        imagePullPolicy: Never
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql-service; sleep 2; done;']